app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required
#from flask_wtf import FlaskForm as BaseForm


class LoginForm(FlaskForm):
    """Accepts a nickname and a room."""
    name = StringField('', validators=[Required()])
    room = StringField('')
    submit = SubmitField('')
    

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm
from flask_wtf import FlaskForm as BaseForm
listasalas=[]



@main.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    archivo = open("archivo.txt","a")
    a = "Usuario: " + str(form.name.data) + "  Sala: " + str(form.room.data) + " \n"
    archivo.write(str((a)))
    archivo.close()
    if form.validate_on_submit():
        if not (listasalas):
            listasalas.append(form.room.data)
        else:
            if(verificar(form.room.data)):
                print("ya esta")
            else:
                listasalas.append(form.room.data)
                    
            
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form,lista=listasalas)

@main.route('/registrar', methods=['GET', 'POST'])
def registrar():
    form = LoginForm()
    if form.validate_on_submit():
        if not (listasalas):
            listasalas.append(form.room.data)
        else:
            if(verificar(form.room.data)):
                print("ya esta")
            else:
                listasalas.append(form.room.data)
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('registrar.html', form=form,lista=listasalas)



@main.route('/ingresar', methods=['GET', 'POST'])
def verificar(dato):
    for a in listasalas:
        if(a==dato):
            return True
    return False

@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)

app/templates/chat.html
<html>
    <head>
        <title>Aldair47x {{ room }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Chewy|Marck+Script" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style_paper.css' ) }}">
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.index') }}";
                });
            }
        </script>
    </head>
    <body>
        <div id="wrapper">

                <div id="paper">
            
                    <div id="margin" style="font-family: 'Marck Script', cursive;
                            font-size:32px;">
                            Haz iniciado el chat en la sala -> {{ room }} </div>
                    <textarea id="chat" readonly="readonly" cols="80" rows="20" 
                    style="height: 450px; max-height: 450px; width: 800px;
                        background-color:#FFF;
                        color:#222;
                        font-family: 'Chewy', cursive;
                        font-weight:normal;
                        font-size:16px;
                        resize:none;
                        line-height:40px;
                        padding-left:100px;
                        padding-right:100px;
                        padding-top:45px;
                        padding-bottom:34px;
                        background-image:url(https://static.tumblr.com/maopbtg/E9Bmgtoht/lines.png), url(https://static.tumblr.com/maopbtg/nBUmgtogx/paper.png);
                        background-repeat:repeat-y, repeat;
                        -webkit-border-radius:12px;
                        border-radius:12px;
                        -webkit-box-shadow: 0px 2px 14px #000;
                        box-shadow: 0px 2px 14px #000;
                        border-top:1px solid #FFF;
                        border-bottom:1px solid #FFF;
                        overflow-y: scroll;"> </textarea>
                    <br><br>
                </div>
                <input id="text" placeholder="Enter your message here"  style=" width: 800px;  padding: 10px 20px;
                        box-sizing: border-box;
                        background: rgb(212, 207, 124);
                        border: 0;
                        color:#222;
                        display: block;
                        width: 100%;
                        background: rgb(212, 207, 124);
                        border-bottom: 1px solid rgb(48, 67, 175);
                        font-family: 'Chewy', cursive;
                        font-weight:normal;
                        font-size:16px;">

                <a href="#" onclick="leave_room();">Leave this room</a>
        </div>

    </body>
        
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Aldair47x</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='images/icons/favicon.ico' ) }}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css' ) }}" >
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='fonts/Linearicons-Free-v1.0.0/icon-font.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animate/animate.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css') }}">>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animsition/css/animsition.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/select2/select2.min.css') }}">>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/daterangepicker/daterangepicker.css') }}">
<!--===============================================================================================-->
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/util.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
<!--===============================================================================================-->
</head>
<body>


	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form" method="POST">
					{{ form.hidden_tag() }}
                <h1 style="font-family: 'Berkshire Swash', cursive;
                            margin: 30px;">Final project distributed systems</h1>
				
				<div class="wrap-input100 validate-input" data-validate="Name is required">
					<input class="input100" class="lnr lnr-user" id="name" name="name" type="text"  placeholder="Nickname">
					<label class="label-input100" for="name">
						<span class="lnr lnr-user" style="margin: 0px 0px 0px 0px;"></span>  
						<div style="visibility: hidden;">
														
                    		
						</div>
                      
                        
                    </label>
                    
				</div>
				

				<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<input class="input100" id="email" type="email" name="email" placeholder="Email">
						<label class="label-input100" for="email">
							<span class="lnr lnr-envelope"></span>
						</label>
				</div>
	
					<div class="wrap-input100 validate-input">
						<input class="input100" id="pass" type="password" name="pass" placeholder="Password">
						<label class="label-input100" for="pass">
							<span class="lnr lnr-mustache"></span>
						</label>
					</div>
		
					<div class="wrap-input100 validate-input" data-validate = "Age is required: 20">
						<input class="input100" id="edad" type="date" name="edad" placeholder="Date">
						<label class="label-input100" for="edad">
							<span class="lnr lnr-calendar-full"></span>
						</label>
					</div>
	
					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input  class="input100" id="genero" type="checkbox" name="Masculino" placeholder="Genre" style="margin: 0px 0px 0px 200px;">
						<label class="label-input100" for="genre">
								<select style="margin: 0px 0px 0px 20px;" >
										<option value="Femenino">Female</option>
										<option value="Masculino">Male</option>
								</select>
						</label>
						
					</div>
                
                <div class="wrap-input100 validate-input" data-validate="Name is required">
                        <input class="input100" id="room" type="text" name="room" placeholder="Room Name">
                        <label class="label-input100" for="room">
								<span class="lnr lnr-users" style="margin: 0px 0px 0px 20px;"></span>  
								<div style="visibility: none;">
								
								</div>
                        </label>
                        
                </div>


				<div class="container-contact100-form-btn">
                        <div class="wrap-contact100-form-btn">
                            <div class="contact100-form-bgbtn"></div>
                            <button type="submit" class="contact100-form-btn" >
                            Submit 
							</button>
							
						</div>
						
				

				
			</form>
		</div>
	</div>



	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/animsition/js/animsition.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/bootstrap/js/popper.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/select2/select2.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/daterangepicker/moment.min.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/daterangepicker/daterangepicker.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/countdowntime/countdowntime.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>



    </body>
</html>

app/templates/registrar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Aldair47x</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='images/icons/favicon.ico' ) }}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css' ) }}" >
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='fonts/Linearicons-Free-v1.0.0/icon-font.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animate/animate.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css') }}">>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animsition/css/animsition.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/select2/select2.min.css') }}">>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/daterangepicker/daterangepicker.css') }}">
<!--===============================================================================================-->
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/util.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
<!--===============================================================================================-->
<script language="JavaScript">
		function habilita(){
			$(".inputText").removeAttr("disabled");
		}
	 
		function deshabilita(){
			$(".inputText").attr("disabled","disabled");
		}
	</script>
</head>
<body>

	<div class=""container>
		<div class="row justify-content-center">
			<div class="col-md-8 col-sm-12 col-offset-md-2">
					<div class="container-contact100">
							<div class="wrap-contact100">
								<form class="contact100-form validate-form" method="POST">
										{{ form.hidden_tag() }}
									<h1 style="font-family: 'Berkshire Swash', cursive;
												margin: 30px;">Flask chat with SOCKET IO</h1>
									
									
									<div class="wrap-input100 validate-input" data-validate = "Valid name">
										<input class="input100" id="nombre" type="text" name="nombre" placeholder="Name">
											<label class="label-input100" for="nombre">
												<span class="lnr lnr-smile"></span>
											</label>
									</div>

									<div class="wrap-input100 validate-input" data-validate = "Valid last name">
											<input class="input100" id="Apellido" type="text" name="Apellido" placeholder="Last name">
												<label class="label-input100" for="Apellido">
													<span class="lnr lnr-spell-check"></span>
												</label>
									</div>
					
									<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
										<input class="input100" id="email" type="email" name="email" placeholder="Email">
											<label class="label-input100" for="email">
												<span class="lnr lnr-envelope"></span>
											</label>
									</div>
						
										<div class="wrap-input100 validate-input">
											<input class="input100" id="pass" type="password" name="pass" placeholder="Password">
											<label class="label-input100" for="pass">
												<span class="lnr lnr-mustache"></span>
											</label>
										</div>
							
										<div class="wrap-input100 validate-input" data-validate = "Age is required: 20">
											<input class="input100" id="edad" type="date" name="edad" placeholder="Date">
											<label class="label-input100" for="edad">
												<span class="lnr lnr-calendar-full"></span>
											</label>
										</div>
						
										<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
											<input  class="input100" id="genero" type="checkbox" name="Masculino" placeholder="Genre" >
											<label class="label-input100" for="genre">
													<select style="margin: 0px 0px 0px 20px;" >
															<option value="Femenino">Female</option>
															<option value="Masculino">Male</option>
													</select>
											</label>
											
										</div>
										

					
									<div class="container-contact100-form-btn">
											<div class="wrap-contact100-form-btn">
												<div class="contact100-form-bgbtn"></div>
												<button type="submit" class="contact100-form-btn" >
												Submit 
												</button>
												
                                    </div>
                                    </br>

                                    
											
									
					
									
                                </form>
                                <a href="/" >Ingresar</a>
                            </div>
                            
                        </div>
                        
			</div>
		</div>
	</div>

	



	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/animsition/js/animsition.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/bootstrap/js/popper.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/select2/select2.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/daterangepicker/moment.min.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/daterangepicker/daterangepicker.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='vendor/countdowntime/countdowntime.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	<script>
		function cambio(){
			var valor_select = document.getElementById('inputGroupSelect01').value;
			if(valor_select == "crear"){
				document.getElementById('room').style.display = 'block';
			}
			else{
				document.getElementById('room').style.display = 'none';
				document.getElementById('room').value = valor_select;
			}
		}
	</script>

    </body>
</html>